language: cpp
compiler:
  - g++
# sudo: false

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install libbsd-dev

install:
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make testall

